<text x="215" y="35" class="layout">Data singletons</text>
<path class="layout" d="M 215 38 L 461 352 M 215 38 L 145 159" />
<text x="650" y="35" class="layout">Logo, not visible in &lt;image&gt;</text>
<path class="layout" d="M 650 40 L 730 82" />
<text x="270" y="575" class="layout">Title</text>
<path class="layout" d="M 270 558 L 272 528" />
<text x="480" y="575" class="layout">Sub Title</text>
<path class="layout" d="M 400 550 L 435 568" />
